### PR TITLE
Set maximum bit width for classical operations according to pytket support

### LINKED ISSUE #165: `UINTMAX` is hard-coded as `2^32 - 1`
> `UINTMAX` is hard-coded as $2^{32} - 1$, but if we have non-32-bit registers we'd want a different value. In pytket's QASM converters there is a `maxwidth` parameter that can be used to set this value (defaulting to 32). Could something similar be done here?

_Originally posted by @cqc-alec in https://github.com/CQCL/pytket-phir/pull/162#discussion_r1559027873_

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

See also https://github.com/CQCL/tket/pull/1456 .

Fixes #165 .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist

- [x] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the changelog with any user-facing changes

### CODE REVIEW

**Review by qartik — APPROVED** [review]
LGTM.

**Comment by qartik** [comment]
One question, do we still require a `maxwidth` parameter for pytket-phir as mentioned in #165? 

To me it seems it's being fully handled in pytket and pulled in here with your change in this PR. So perhaps not.

**Comment by cqc-alec** [comment]
> One question, do we still require a `maxwidth` parameter for pytket-phir as mentioned in #165?
> 
> To me it seems it's being fully handled in pytket and pulled in here with your change in this PR. So perhaps not.

I agree, we probably don't need that parameter now.

**Comment by qartik** [comment]
Feel free to merge. I can make a new release once https://github.com/CQCL/tket/pull/1456 is merged and released so we can do integration testing.

**Comment by qartik** [comment]
In that case, let me take it from here and make a new release.

**Comment by cqc-alec** [comment]
Thanks!

**Pull request merged**
